# Generated by Django 3.0.8 on 2020-07-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0060_auto_20200724_2157'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='direcciones',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='listadeseos',
            options={'verbose_name': 'Lista de Deseos', 'verbose_name_plural': 'Lista de Deseos'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='telefonos',
            options={'verbose_name': 'Telefono', 'verbose_name_plural': 'Telefonos'},
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetallesCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.ImageField(default=0, upload_to='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Productos')),
            ],
            options={
                'verbose_name': 'Detalle Carrito',
                'verbose_name_plural': 'Detalles del Carrito',
            },
        ),
    ]
