# Generated by Django 3.0.8 on 2020-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200726_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescarrito',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
