# Generated by Django 3.0.8 on 2020-07-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_detallescarrito_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallescarrito',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Carrito'),
        ),
    ]
