# Generated by Django 3.0.8 on 2020-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200728_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
