# Generated by Django 3.0.8 on 2020-07-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200728_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadeseos',
            name='slug',
        ),
    ]
