# Generated by Django 3.0.8 on 2020-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_iconos'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconos',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
