# Generated by Django 3.0.8 on 2020-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_iconos_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconos',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
