# Generated by Django 3.0.8 on 2020-07-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='Tiendas/logos')),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=300)),
                ('dir_map', models.TextField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
