# Generated by Django 3.0.8 on 2020-07-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='hash',
        ),
        migrations.AddField(
            model_name='tiendas',
            name='hashes',
            field=models.CharField(default=0, max_length=64, unique=True),
        ),
    ]
