# Generated by Django 3.0.8 on 2020-07-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_auto_20200713_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('icono', models.CharField(max_length=30)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas')),
            ],
        ),
    ]
