# Generated by Django 3.0.8 on 2020-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendas',
            name='hashes',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
