# Generated by Django 3.0.8 on 2020-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_auto_20200714_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='ciudad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tiendas',
            name='provincia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
