# Generated by Django 3.0.8 on 2020-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_auto_20200714_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='correo',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
