# Generated by Django 3.0.8 on 2020-07-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_tiendas_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='Teindas/Marcas')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas')),
            ],
        ),
    ]
