# Generated by Django 3.0.8 on 2020-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_marcas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Teindas/Marcas'),
        ),
    ]
