# Generated by Django 3.0.8 on 2020-07-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_auto_20200714_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Tiendas/Adds')),
                ('estado', models.BooleanField(default=False)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas')),
            ],
        ),
    ]
