# Generated by Django 3.0.8 on 2020-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_auto_20200714_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
