# Generated by Django 3.0.8 on 2020-07-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0011_adds_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('detalles_generales', models.TextField(blank=True, null=True)),
                ('detalles_tecnicos', models.TextField(blank=True, null=True)),
                ('garantia_y_mas', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Marcas')),
            ],
        ),
    ]
