# Generated by Django 3.0.8 on 2020-07-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0013_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='adds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.Adds'),
        ),
    ]
