# Generated by Django 3.0.8 on 2020-07-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0014_productos_adds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Tienda/Productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.Productos')),
            ],
        ),
    ]
