# Generated by Django 3.0.8 on 2020-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0015_productofotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
