# Generated by Django 3.0.8 on 2020-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0016_productos_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo_interno',
            field=models.IntegerField(default=0),
        ),
    ]
