# Generated by Django 3.0.8 on 2020-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0017_productos_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='vertical',
            field=models.BooleanField(default=True),
        ),
    ]
