# Generated by Django 3.0.8 on 2020-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0018_adds_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='horizontal',
            field=models.BooleanField(default=True),
        ),
    ]
