# Generated by Django 3.0.8 on 2020-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0019_adds_horizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas'),
        ),
        migrations.AlterField(
            model_name='adds',
            name='horizontal',
            field=models.BooleanField(default=False),
        ),
    ]
