# Generated by Django 3.0.8 on 2020-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0020_auto_20200714_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tienda/Productos'),
        ),
    ]
