# Generated by Django 3.0.8 on 2020-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0021_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
