# Generated by Django 3.0.8 on 2020-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0025_productofotos_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='pais',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='ciudad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='provincia',
            field=models.IntegerField(default=0),
        ),
    ]
