# Generated by Django 3.0.8 on 2020-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0027_tiendas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
