# Generated by Django 3.0.8 on 2020-07-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0029_productos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas'),
        ),
    ]
