# Generated by Django 3.0.8 on 2020-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0030_categorias_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.ImageField(upload_to='iconos'),
        ),
    ]
