# Generated by Django 3.0.8 on 2020-07-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0031_auto_20200719_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
