# Generated by Django 3.0.8 on 2020-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0033_auto_20200719_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='iconos'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Teindas/Marcas'),
        ),
    ]
