# Generated by Django 3.0.8 on 2020-07-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_iconos'),
        ('Tienda', '0034_auto_20200719_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracion.Iconos'),
        ),
    ]
