# Generated by Django 3.0.8 on 2020-07-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0035_auto_20200719_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='icono',
        ),
    ]
