# Generated by Django 3.0.8 on 2020-07-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0037_categorias_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='icono',
        ),
    ]
