# Generated by Django 3.0.8 on 2020-07-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_auto_20200719_1004'),
        ('Tienda', '0038_remove_categorias_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='icono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracion.Iconos'),
        ),
    ]
