# Generated by Django 3.0.8 on 2020-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0041_categorias_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='imagen',
            field=models.ImageField(upload_to='Tienda/Adds'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tienda/Marcas'),
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='logo',
            field=models.ImageField(upload_to='Tienda/logos'),
        ),
    ]
