# Generated by Django 3.0.8 on 2020-07-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0043_marcas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='estad0',
            field=models.BooleanField(default=True),
        ),
    ]
