# Generated by Django 3.0.8 on 2020-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0044_marcas_estad0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='estad0',
            new_name='estado',
        ),
    ]
