# Generated by Django 3.0.8 on 2020-07-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0047_categorias_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='usuario',
        ),
    ]
