# Generated by Django 3.0.8 on 2020-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0049_tiendacategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='estado',
        ),
        migrations.AddField(
            model_name='tiendacategoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
