# Generated by Django 3.0.8 on 2020-07-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0050_auto_20200720_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiendacategoria',
            old_name='categotia',
            new_name='categoria',
        ),
    ]
