# Generated by Django 3.0.8 on 2020-07-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0051_auto_20200720_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
