# Generated by Django 3.0.8 on 2020-07-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0052_remove_productos_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='kardex',
            options={'verbose_name': 'Kardex', 'verbose_name_plural': 'Kardex'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='productofotos',
            options={'verbose_name': 'Fotos de Producto', 'verbose_name_plural': 'Fotos de Producto'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='tiendacategoria',
            options={'verbose_name': 'Relacion Tienda y Categoria', 'verbose_name_plural': 'Relaciones Tiendas y Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tiendas',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
    ]
