# Generated by Django 3.0.8 on 2020-07-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0054_auto_20200724_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.Tiendas'),
        ),
    ]
