# Generated by Django 3.0.8 on 2020-07-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0057_auto_20200724_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcas',
            name='imagen',
        ),
    ]
