# Generated by Django 3.0.8 on 2020-07-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0058_remove_marcas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tienda/Marcas'),
        ),
    ]
