# Generated by Django 3.0.8 on 2020-07-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0059_marcas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Tienda/Marcas'),
        ),
    ]
