# Generated by Django 3.0.8 on 2020-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0060_auto_20200724_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
