# Generated by Django 3.0.8 on 2020-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0062_auto_20200730_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
