# Generated by Django 3.0.8 on 2020-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0064_auto_20200802_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
