# Generated by Django 3.0.8 on 2020-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0067_auto_20200802_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productofotos',
            name='imagen',
            field=models.ImageField(help_text='Imagen de 600 * 600', upload_to='Tienda/Productos'),
        ),
    ]
