# Generated by Django 3.0.8 on 2020-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0068_auto_20200803_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='color',
            field=models.CharField(default='Negro', max_length=50),
        ),
    ]
