# Generated by Django 3.0.8 on 2020-08-03 16:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0069_productos_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo_color',
            field=colorfield.fields.ColorField(default='#269300', max_length=30),
        ),
    ]
