# Generated by Django 3.0.8 on 2020-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='slider')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valorPromocion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valorSinPromocion', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
