# Generated by Django 3.0.8 on 2020-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200727_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='mensajeBoton',
            field=models.CharField(blank=True, default='Llévame allá', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='valorPromocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='slider',
            name='valorSinPromocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
