# Generated by Django 3.0.8 on 2020-07-27 16:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_slider_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='colorBoton',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
