# Generated by Django 3.0.8 on 2020-07-27 16:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_slider_colorboton'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorInterfaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', colorfield.fields.ColorField(default='#333333', max_length=18)),
                ('page', colorfield.fields.ColorField(default='#cccccc52', max_length=18)),
                ('botons', colorfield.fields.ColorField(default='#ff3600', max_length=18)),
            ],
        ),
    ]
