# Generated by Django 3.0.8 on 2020-07-27 16:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_colorinterfaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorinterfaz',
            name='menu',
            field=colorfield.fields.ColorField(default='#ff3600', max_length=18),
        ),
    ]
