# Generated by Django 3.0.8 on 2020-07-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_calificarproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificarproductos',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
