# Generated by Django 3.0.8 on 2020-07-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_calificarproductos_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificarproductos',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
