# Generated by Django 3.0.8 on 2020-07-30 16:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20200728_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorinterfaz',
            name='header_texto',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
