BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX

                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXX XXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX
                            XXXXX
                            XXXXXXXX
                            XXXXXXX
                            XXX XXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                            XXXXX
                            XXXXXXXX
                        XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXXXXX

        BBB BBBBBBBB BB BBBBBBBBB
            XXX XXXXXXXXX
            BBB BBBB BB BBBBB
                BB BBBBBBBBBBBBB BB BBBBBBBB
                    XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                BBBBB
            BBBBBB
            XX XXXXXXXXX

            X
            XXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
            X


            XXXXXXXXXXX
                XXX
                XXX
                XXX
                XXXXXXX
                X XXXXX  X
                BB BBB BBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                BBBBB
                XXX
                XXX
                XXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX X X
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX

            XX
        BBBBBB
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXX
        X XX
    X XX
    XXXXXXXXX
BBBBBBBB
