BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBB
    BBBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
                XXX XXXXXXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX

                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXX XXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXX X XXXXXXXXX X XXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX
                            XXXXX
                            XXXXXXXX
                            XXXXXXX
                            XXX XXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                                XXXXXXXXX
                            XXXXX
                            XXXXXXXX
                        XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

BBBBBBBB
BBBBB BBBBBBB
XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXXX
    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXXXXX

        BBB BBBBBB BB BBBBBBB
            XXXXXXXXXXX
                XXX
                XFFFFFFFFFFFFFFFFXX
                XXX
                XBBBB BBBBBBBBBBB X BBBBBBBBB BBBBBBBBBBBBBBBB XBBBBBB BBBBBBBBBBBBB XX
                XXX
                XXX
                XXX
                BB BBBBBBBBBBBBB
                    XXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                    XXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX X X
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX X
            XX
        BBBBBB
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXX
        X XX
    X XX
    XXXXXXXXX
BBBBBBBB
